@baseUrl = https://localhost:7213


### ROOMS

### Vrati sve sobe
GET {{baseUrl}}/api/rooms/GetRooms
Accept: application/json

### Dodaj sobu
POST {{baseUrl}}/api/rooms/AddRoom
Content-Type: application/json

{
    "naziv" : "E1",
    "raspored" : "((1:12.23.42.11, ,2:23.23.11.12),(3:12.23.42.11, 4:23.23.11.12, ))",
    "capacity" : 4
}

###

### ACTIVITES

### Vrati sve aktivnosti
GET {{baseUrl}}/api/activities/GetActivities
Accept: application/json

### Dodaj aktivnost
POST {{baseUrl}}/api/activities/AddActivity
Content-Type: application/json

{
    "name" : "Programski prevodioci LV1",
    "vlrids" : [
        "Eclipse"
    ]
}

###

### Sessions

### Vrati sve sesije
GET {{baseUrl}}/api/sessions/GetSessions
Accept: application/json

### Dodaj sobu
POST {{baseUrl}}/api/sessions/AddSession
Content-Type: application/json

{
    "roomId": 8,
    "activityId": 11,
    "datum": "2026-02-15",
    "vremePocetka": "12:00:00",
    "vremeKraja": "16:00:00",
    "stanje": 0,
    "automatskiPocetak": false,
    "automatskiKraj": false,
    "automatskoStanjeZavrsavanja": 4
}

###

### VLRController

@session = 19

### Proglasi sesiju za next
PUT {{baseUrl}}/api/vlr/PromoteAsNext?sessionId={{session}}
Content-Type: application/json

### Aktiviraj next sesiju
PUT {{baseUrl}}/api/vlr/Activate?sessionId={{session}}
Content-Type: application/json
###

### Pokrene zavrsavanje za aktivnu sesiju
PUT {{baseUrl}}/api/vlr/Fade?sessionId={{session}}
Content-Type: application/json
###

### Ugasi sesiju
PUT {{baseUrl}}/api/vlr/Terminate?sessionId={{session}}
Content-Type: application/json
###

### Provide nekom korisniku
PUT {{baseUrl}}/api/vlr/Provide?sessionId=20&seatId=2&userId=1004
Content-Type: application/json

### Release od korisnika
PUT {{baseUrl}}/api/vlr/Release?sessionId=19&userId=1002
Content-Type: application/json