@baseUrl = http://localhost:5131


### ROOMS

### Vrati sve sobe
GET {{baseUrl}}/api/rooms/GetRooms
Accept: application/json

### Dodaj sobu
POST {{baseUrl}}/api/rooms/AddRoom
Content-Type: application/json

{
    "naziv" : "R1",
    "raspored" : "((1:12.23.42.11, ,2:23.23.11.12),(3:12.23.42.11, 4:23.23.11.12, ))",
    "capacity" : 4
}

###

### ACTIVITES

### Vrati sve aktivnosti
GET {{baseUrl}}/api/activities/GetActivities
Accept: application/json

### Dodaj aktivnost
POST {{baseUrl}}/api/activities/AddActivity
Content-Type: application/json

{
    "naziv" : "Programski prevodioci LV1",
    "activityClassId" : 3,
    "vlrids" : [
        "Jflex"
    ]
}

###

### Sessions

### Vrati sve sesije
GET {{baseUrl}}/api/sessions/GetSessions
Accept: application/json

### vrati sesije u sobi
GET {{baseUrl}}/api/sessions/GetSessionsInRoom?roomId=3
Accept: application/json

### Dodaj sobu
POST {{baseUrl}}/api/sessions/AddSession
Content-Type: application/json

{
    "roomId": 3,
    "aktivnostId": 3,
    "datum": "2026-03-20",
    "vremePocetka": "15:00:00",
    "vremeKraja": "20:30:00",
    "automatskiPocetak": false,
    "automatskiKraj": false,
    "automatskoKrajnjeStanje": 4
}

###

### VLRController

@session = 2

### Proglasi sesiju za next
PUT {{baseUrl}}/api/vlr/PromoteAsNext?sessionId={{session}}
Content-Type: application/json

### Aktiviraj next sesiju
PUT {{baseUrl}}/api/vlr/Activate?sessionId={{session}}
Content-Type: application/json
###

### Pokrene zavrsavanje za aktivnu sesiju
PUT {{baseUrl}}/api/vlr/Fade?sessionId={{session}}
Content-Type: application/json
###

### Ugasi sesiju
PUT {{baseUrl}}/api/vlr/Terminate?sessionId={{session}}
Content-Type: application/json
###

### Provide nekom korisniku
PUT {{baseUrl}}/api/vlr/Provide?sessionId=31&seatId=4&userId=1002
Content-Type: application/json

### Release od korisnika
PUT {{baseUrl}}/api/vlr/Release?sessionId=31&userId=1002
Content-Type: application/json